name: hassfest
on: [push, pull_request]
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
          pip install hassfest
      - name: Verify installation
        run: |
          python -m pip list
      - name: Run hassfest
        run: |
          hassfest
